# name: Should match the template filename and the property in github
# template_name the name of the template in the templates folder
# repo_path: The path in the repo to write the file to
# alternate_paths: Any paths listed here will be treated as the same file and renamed to the main repo_path

# Groups allow inheriting a potentially evolving set of templates for a particular project type without needing to
# constantly update the list of files in the repo settings
# Just set `group:<groupname>` in the repo settings instead
groups:
  - name: base
    templates:
      - dep-review
      - commit-signing

  - name: go
    templates:
      - go-makefile
      - dependabot

  - name: go-ci
    templates:
      - go-test

files:
  - name: commit-signing
    template_name: check-commit-signing.yml
    repo_path: .github/workflows/check-commit-signing.yml
    alternate_paths:
      - .github/workflows/check-commit-signing.yaml

  - name: dep-review
    template_name: dependency-review.yml
    repo_path: .github/workflows/dependency-review.yml
    alternate_paths:
      - .github/workflows/dependency-review.yaml

  - name: dependabot
    template_name: dependabot.yml
    repo_path: .github/dependabot.yml
    alternate_paths:
      - .github/dependabot.yaml

  - name: go-dependabot
    template_name: go-dependabot.yml
    repo_path: .github/dependabot.yml
    alternate_paths:
      - .github/dependabot.yaml

  - name: go-makefile
    template_name: go-makefile
    repo_path: Makefile

  - name: go-test
    template_name: go-test.yml
    repo_path: .github/workflows/go-test.yml
    alternate_paths:
      - .github/go-test.yaml

  - name: prettier
    template_name: prettierrc.yml
    repo_path: .prettierrc.yml
    alternate_paths:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.json5
      - .prettierrc.yaml
      - .prettierrc.js
      - .prettierrc.js
      - .prettier.config.js
      - .prettierrc.mjs
      - .prettier.config.mjs
      - .prettierrc.cjs
      - .prettier.config.cjs
      - .prettierrc.toml

variables:
  COMPANY_NAME: "Chia Network Inc."
  CGO_ENABLED: "0"
  DEPENDABOT_GOMOD_PULL_REQUEST_LIMIT: "10"
  DEPENDABOT_GOMOD_REBASE_STRATEGY: "auto"
  DEPENDABOT_GOMOD_DIRECTORY: "/"
  DEPENDABOT_GOMOD_REVIEWERS: "[\"cmmarslender\", \"starttoaster\"]"
  DEPENDABOT_PIP_PULL_REQUEST_LIMIT: "10"
  DEPENDABOT_PIP_REBASE_STRATEGY: "auto"
  DEPENDABOT_PIP_DIRECTORY: "/"
  DEPENDABOT_PIP_REVIEWERS: "[\"emlowe\", \"altendky\"]"
  DEPENDABOT_ACTIONS_PULL_REQUEST_LIMIT: "10"
  DEPENDABOT_ACTIONS_REBASE_STRATEGY: "auto"
  DEPENDABOT_ACTIONS_DIRECTORY: "/"
  DEPENDABOT_ACTIONS_REVIEWERS: "[\"cmmarslender\", \"Starttoaster\", \"pmaslana\"]"
  DEPENDABOT_NPM_PULL_REQUEST_LIMIT: "10"
  DEPENDABOT_NPM_REBASE_STRATEGY: "auto"
  DEPENDABOT_NPM_DIRECTORY: "/"
  DEPENDABOT_NPM_REVIEWERS: "[\"cmmarslender\", \"ChiaMineJP\"]"
  DEPENDABOT_CARGO_DIRECTORY: "/"
  DEPENDABOT_CARGO_PULL_REQUEST_LIMIT: "10"
  DEPENDABOT_CARGO_REBASE_STRATEGY: "auto"
